apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-service
  labels:
    app.kubernetes.io/name: banking-service
data:
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banking_db
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_KAFKA_CONSUMER_GROUP_ID: banking-service
  BANKING_SERVICE_TRANSACTIONS_KAFKA_TOPIC: account-transactions
  BANKING_SERVICE_TRANSACTIONS_KAFKA_DEAD_LETTER_TOPIC: account-transactions-dlq
  BANKING_SERVICE_TRANSACTIONS_SYSTEM_DEFAULT_MAJOR_DISPLAY_CURRENCY: USD
  BANKING_SERVICE_KAFKA_ENABLED: "true"
  JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=75
