apiVersion: v1
kind: Secret
metadata:
  name: banking-service
  labels:
    app.kubernetes.io/name: banking-service
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: change-me
  BANKING_SERVICE_SECURITY_JWT_PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    replace-with-public-key-content
    -----END PUBLIC KEY-----
